name: app-build-action
on:
  push:
    tags:
      - "v*"

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ steps.version.outputs.VERSION }}"
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk

  build-windows:
    needs: build-android
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop

      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter pub get

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build Windows
        run: |
          cd simple_live_app
          flutter_distributor package --platform windows --targets zip --skip-clean

      - name: Show build output
        shell: pwsh
        run: Get-ChildItem -LiteralPath simple_live_app\build\dist -Recurse -File | ForEach-Object { $_.FullName }

      - name: Get version from tag
        id: version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Append to Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ steps.version.outputs.VERSION }}"
          append_body: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            simple_live_app/build/dist/*/*.zip
